### PR TITLE
fix package not found issue

### PR DESCRIPTION
**Pull request by abhishek97**
Fix : https://github.com/coding-blocks/content-downloader/issues/3

### CODE REVIEW

**Comment by championswimmer** [comment]
@nikhilkumarsingh is this a py2 vs py3 thing ?

**Comment by abhishek97** [comment]
@championswimmer  I believe this is has something to do with the version of `requests` package.
here : https://stackoverflow.com/questions/28904607/cannot-import-requests-packages-urllib3-util-retry

**Comment by nikhilkumarsingh** [comment]
I dont think this qualifies as a fix. 
User must use latest version of requests package.

**Comment by abhishek97** [comment]
@nikhilkumarsingh yes, so in the recent version we need to 

```
from urllib3.util import Retry
```

right?

**Comment by nikhilkumarsingh** [comment]
No. 
`from requests.packages.urllib3.util.retry import Retry`
is working in latest version.

**Comment by abhishek97** [comment]
@championswimmer  @nikhilkumarsingh  It is so that the version i get from `pip install -r ctld` is `2.16.0` (default you'll get on mac ) , changed `requirements.txt` to specify a version to use. This should fix this.

**Pull request merged**
