### PR TITLE
gui for content downloader 

### PR DESCRIPTION
**Pull request by akansh97531**
gui opens with command : python tk.py

### CODE REVIEW

**Comment by championswimmer** [comment]
@nikhilkumarsingh review

**Comment by akansh97531** [comment]
okay sir i will work on 1,2,4,5 , and there is no need of :
from multiprocessing import Queue in gui_download.py
i was trying something so , i forgot to remove it

**Comment by akansh97531** [comment]
all improvements done with support of python2

**Comment by nikhilkumarsingh** [comment]
Nice work @akansh97531 
1. Please complete the task 2 as well since it makes code more readable and maintainable.
2. Also, you can set the entry point for `gui.py` as `ctdl-gui` .
3. Please follow the code for [clix](https://github.com/coding-blocks/clix) to understand how to add icon in a Tkinter application. (You can use a `png` image and will have to mention file path in `MANIFEST.in` like [this](https://github.com/coding-blocks/clix/blob/master/MANIFEST.in) otherwise it will not get recognized by package manager.)

**Comment by akansh97531** [comment]
changes done ! @nikhilkumarsingh

**Comment by nikhilkumarsingh** [comment]
Very poor formatting @akansh97531 .
Simply find and replace will not do.
See [this](https://github.com/coding-blocks/clix/blob/master/clix/gui.py) script as reference.
Don't make hurry in this task. It is only for readability and will help in longer run.

**Comment by nikhilkumarsingh** [comment]
1. You haven't deleted `tk.py` in your code.
2. Rename `gui_download.py` to `gui_downloader.py`
3. Upload any icon of your choice for now.

**Comment by akansh97531** [comment]
please review the formatting now , added some comments to help understand better
if you want any more changes please tell me

**Comment by nikhilkumarsingh** [comment]
The only problem I have is with the spaces and commas. Please use the style as used in this [script](https://github.com/coding-blocks/clix/blob/master/clix/gui.py) . You have used spaces unnecessarily  at some places and never used it at others.
Follow the reference script strictly.

**Comment by akansh97531** [comment]
@nikhilkumarsingh  i have done it manually now

**Comment by nikhilkumarsingh** [comment]
The code looks much better now.
1. Remove useless spaces after `(` and before `)` .
2. Rename the ctdl gui window from `Content Downloader` to `ctdl` only.
3. Make a consistent format for each function, i.e:
   def <func-name>(<arguments>):
          """
          <short-description of function>
          """
          <global varibales>
          .....

**Comment by akansh97531** [comment]
@nikhilkumarsingh  done!!

**Comment by akansh97531** [comment]
@nikhilkumarsingh  please review

**Comment by nikhilkumarsingh** [comment]
All looks fine @akansh97531 
Update the readme with info about `ctdl-gui`.
You can also add a gif showing usage of ctdl-gui.

**Comment by akansh97531** [comment]
@nikhilkumarsingh  added info and gui

**Comment by nikhilkumarsingh** [comment]
I am getting this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/ctdl-gui", line 11, in <module>
    load_entry_point('ctdl==1.4.5', 'console_scripts', 'ctdl-gui')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/ctdl/gui.py", line 40, in <module>
    img = Image("photo", file="icon.gif")
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3329, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "icon.gif": no such file or directory
```

when I open `ctdl-gui` from a directory other than the package directory. It seems to be a problem of relative imports. Please fix it.

**Comment by akansh97531** [comment]
okay i will look into it

**Pull request merged**
